import { Category, Service, User } from './data.model';

const services: Service[] = [
  { id: '1', name: 'Sửa board', price: 50000 },
  { id: '2', name: 'Sửa cốt máy giặt', price: 250000 },
  { id: '3', name: 'Sửa motor xả nước', price: 450000 },
  { id: '4', name: 'Sửa van nước cấp', price: 240000 },
  { id: '5', name: 'Sửa phao cảm biến', price: 350000 },
  { id: '6', name: 'Sửa ty treo', price: 90000 },
  { id: '7', name: 'Sửa motor', price: 30000 },
  { id: '8', name: 'Vệ sinh máy', price: 90000 },
  { id: '9', name: 'Sửa dây curoa ', price: 40000 },
  { id: '10', name: 'Sửa tụ máy', price: 50000 },
  { id: '11', name: 'Hư cao áp ', price: 200000 },
  { id: '12', name: 'Hư nguồn ', price: 250000 },
  { id: '13', name: 'Hư bo khiển', price: 300000 },
  { id: '14', name: 'Thay cổng HDMI', price: 350000 },
  { id: '15', name: 'Thay mắt thần', price: 530000 },
  { id: '16', name: 'Thay loa tivi', price: 570000 },
  { id: '17', name: 'Thay phim màn hình', price: 250000 },
  { id: '18', name: 'Thay đèn LED cho', price: 950000 },
  { id: '19', name: 'Thay màn hình', price: 650000 },
  { id: '20', name: 'Vệ sinh tivi', price: 60000 },
  { id: '21', name: 'Thay ron', price: 580000 },
  { id: '22', name: 'Vệ sinh tủ lạnh', price: 540000 },
  { id: '23', name: 'Thay thế các linh kiện', price: 450000 },
  { id: '24', name: 'Sửa tủ đông', price: 80000 },
  { id: '25', name: 'Sửa tủ mát', price: 840000 },
  { id: '26', name: 'Thay quạt dàn nóng', price: 70000 },
  { id: '27', name: 'Thay block tủ lạnh', price: 70000 },
  { id: '28', name: 'Hàn dàn + nạp gas', price: 45000 },
  { id: '29', name: 'Thay điện trở', price: 45000 },
  { id: '30', name: 'Sửa board', price: 45000 },
  { id: '31', name: 'Sửa mất nguồn', price: 453000 },
  { id: '32', name: 'Sửa board dàn lạnh (mono)', price: 730000 },
  { id: '33', name: 'Sửa board dàn lạnh (inverter)', price: 730000 },
  { id: '34', name: 'Thay cảm biến to phòng/dàn', price: 73000 },
  { id: '35', name: 'Thay mắt nhận tín hiệu', price: 710000 },
  { id: '36', name: 'Thay tụ quạt dàn lạnh', price: 70000 },
  { id: '37', name: 'Thay mô tơ lá đảo gió', price: 370000 },
  { id: '38', name: 'Thay tụ quạt dàn nóng', price: 670000 },
  { id: '39', name: 'Nạp ga', price: 80000 },
  { id: '40', name: 'Vệ sinh máy lạnh', price: 280000 },
  { id: '41', name: 'Thay cục sóng', price: 840000 },
  { id: '42', name: 'Sửa board', price: 82000 },
  { id: '43', name: 'Thay cầu chì', price: 86000 },
  { id: '44', name: 'Thay Timer', price: 18000 },
  { id: '45', name: 'Sơn + xử lý rỉ sét', price: 98000 },
  { id: '46', name: 'Lá chắn sóng', price: 88000 },
  { id: '47', name: 'Moter đĩa', price: 84000 },
  { id: '48', name: 'Đĩa thuỷ tinh lò vi sóng', price: 100000 },
  { id: '49', name: 'Biến áp', price: 100000 },
  { id: '50', name: 'Tụ lò vi sóng', price: 150000 },
  { id: '51', name: 'Không nhận nồi', price: 120000 },
  { id: '52', name: 'Sửa dây', price: 100000 },
  { id: '53', name: 'Sửa cảm ứng', price: 80000 },
  { id: '54', name: 'Thay quạt', price: 80000 },
  { id: '55', name: 'Vùng nấu không hoạt động', price: 300000 },
  { id: '56', name: 'Bếp từ kêu to', price: 300000 },
  { id: '57', name: 'Lỗi treo máy', price: 300000 },
  { id: '58', name: 'Sửa nguồn', price: 300000 },
  { id: '59', name: 'Thay thanh nhiệt', price: 300000 },
  { id: '60', name: 'Thay kính lò nướng', price: 50000 },
  { id: '61', name: 'Sửa nguồn', price: 50000 },
  { id: '62', name: 'Sửa đèn tín hiệu', price: 450000 },
  { id: '63', name: 'Sửa đèn trong lò', price: 450000 },
  { id: '64', name: 'Đánh lửa có vấn đề', price: 450000 },
  { id: '65', name: 'Làm nóng bị mài mòn', price: 450000 },
  { id: '66', name: 'Nhiệt độ không đúng', price: 450000 },
  { id: '67', name: 'Vệ sinh lò nướng', price: 50000 },
  { id: '68', name: 'Vệ sinh lò', price: 50000 },
  { id: '69', name: 'Thay tụ điện', price: 500000 },
  { id: '70', name: 'Hư cuộn dây đồng', price: 500000 },
  { id: '71', name: 'Thay jack cắm', price: 520000 },
  { id: '72', name: 'Sửa nguồn', price: 650000 },
  { id: '73', name: 'Sửa âm lượng', price: 650000 },
  { id: '74', name: 'Thay thế motor', price: 50000 },
  { id: '75', name: 'Sửa mạch điều khiển', price: 750000 },
  { id: '76', name: 'Sửa nguồn điện', price: 73000 },
  { id: '77', name: 'Máy hút bị yếu', price: 350000 },
  { id: '78', name: 'Máy chạy nhưng không hút', price: 50000 },
];

const categories: Category[] = [
  {
    id: '1',
    name: 'Sửa máy giặt',
    thumbnail: 'cate-1.svg',
    services: services.filter((_, index) => index < 10),
  },
  {
    id: '2',
    name: 'Sửa tivi',
    thumbnail: 'cate-2.svg',
    services: services.filter((_, index) => index >= 10 && index < 20),
  },
  {
    id: '3',
    name: 'Sửa tủ lạnh',
    thumbnail: 'cate-3.svg',
    services: services.filter((_, index) => index >= 20 && index < 30),
  },
  {
    id: '4',
    name: 'Sửa máy lạnh',
    thumbnail: 'cate-4.svg',
    services: services.filter((_, index) => index >= 30 && index < 40),
  },
  {
    id: '5',
    name: 'Sửa lò vi sóng',
    thumbnail: 'cate-5.svg',
    services: services.filter((_, index) => index >= 40 && index < 50),
  },
  {
    id: '6',
    name: 'Sửa máy nướng',
    thumbnail: 'cate-6.svg',
    services: services.filter((_, index) => index >= 50 && index < 58),
  },
  {
    id: '7',
    name: 'Sửa lò nướng',
    thumbnail: 'cate-7.svg',
    services: services.filter((_, index) => index >= 58 && index < 67),
  },
  {
    id: '8',
    name: 'Sửa loa vi tính',
    thumbnail: 'cate-8.svg',
    services: services.filter((_, index) => index >= 67 && index < 73),
  },
  {
    id: '9',
    name: 'Sửa máy hút bụi',
    thumbnail: 'cate-9.svg',
    services: services.filter((_, index) => index >= 73 && index < 78),
  },
];

const users: User[] = [
  {
    id: '1',
    distance: 5,
    time: 34,
    phone: '0909123123',
    rating: 4.7,
    name: 'Võ Thành Nhân',
    avatar: 'avatar-0.jpg',
    address: '55B Trần Quang Khải',
    province: 'Q1, TP.HCM',
    categories: categories,
  },
  {
    id: '2',
    distance: 4.3,
    time: 30,
    phone: '0909123675',
    rating: 4.5,
    name: 'Phạm Long',
    avatar: 'avatar-1.png',
    address: '75B Nguyễn Kiệm',
    province: 'Q2, TP.HCM',
    categories: categories,
  },
  {
    id: '3',
    distance: 1.2,
    time: 20,
    phone: '0909134123',
    rating: 3,
    name: 'Dương Nguyên',
    avatar: 'avatar-2.jpg',
    address: '32 Dương Lâm',
    province: 'Gò Vấp, TP.HCM',
    categories: categories,
  },
  {
    id: '4',
    distance: 3.2,
    time: 25,
    phone: '0909657763',
    rating: 3.5,
    name: 'Đỗ Đạt',
    avatar: 'avatar-3.png',
    address: '32 Nhà Gỗ',
    province: 'Tân Bình, TP.HCM',
    categories: categories,
  },
  {
    id: '5',
    distance: 5.3,
    time: 20,
    phone: '0909123123',
    rating: 5,
    name: 'Đặng Nhân',
    avatar: 'avatar-4.png',
    address: '32 Phan Tôn',
    province: 'Q4, TP.HCM',
    categories: categories,
  },
  {
    id: '6',
    distance: 3,
    time: 32,
    phone: '0909123123',
    rating: 4,
    name: 'Hà Tâm',
    avatar: 'avatar-5.png',
    address: '32 Võ Văn Ngân',
    province: 'Thủ Đức, TP.HCM',
    categories: categories,
  },
  {
    id: '7',
    distance: 3.8,
    time: 35,
    phone: '0909123123',
    rating: 4,
    name: 'Lê Văn Đạt',
    avatar: 'avatar-6.png',
    address: '4 Lê Văn Việt',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
  {
    id: '8',
    distance: 8.2,
    time: 45,
    phone: '0909123123',
    rating: 5,
    name: 'Đỗ Trương Đông',
    avatar: 'avatar-7.jpg',
    address: '30 Man Thiện',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
  {
    id: '9',
    distance: 9.2,
    time: 50,
    phone: '0909123123',
    rating: 4,
    name: 'Hà Mẫn Đạt',
    avatar: 'avatar-8.jpg',
    address: '20 Lã Xuân Oai',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
];
const servicesWithCategoryId = services.map((service, index) => {
  if (index < 10) service.categoryId = '1';
  else if (index < 20) service.categoryId = '2';
  else if (index < 30) service.categoryId = '3';
  else if (index < 40) service.categoryId = '4';
  else if (index < 50) service.categoryId = '5';
  else if (index < 58) service.categoryId = '6';
  else if (index < 67) service.categoryId = '7';
  else if (index < 73) service.categoryId = '8';
  else if (index < 78) service.categoryId = '9';
  return service;
});
const predicts: string[] = [
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
  'abc',
  'def',
  'export',
];
const searchHistory = ['máy giặt', 'tủ lạnh', 'sửa tivi'];
export const DATABASE = {
  users,
  services: servicesWithCategoryId,
  categories,
  searchHistory,
  predicts,
};
